#############################################################################
# Makefile for building: qmailcheck
# Generated by qmake (2.01a) (Qt 4.5.3) on: Tue May 25 16:50:28 2010
# Project:  qmailcheck.pro
# Template: app
# Command: /home/hardaker/.madde/0.5/targets/fremantle-qt-0942/bin/qmake -unix -o Makefile qmailcheck.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -O0 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -g -O0 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/linux-g++-gles2 -I. -I../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/include/qt4/QtCore -I../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/include/qt4/QtNetwork -I../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/include/qt4/QtGui -I../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/home/hardaker/.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/lib -Wl,-rpath-link=/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/hardaker/.madde/0.5/targets/fremantle-qt-0942/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qtincoming.cpp \
		incomingmailmodel.cpp \
		mailmsg.cpp \
		foldermodel.cpp moc_foldermodel.cpp
OBJECTS       = main.o \
		qtincoming.o \
		incomingmailmodel.o \
		mailmsg.o \
		foldermodel.o \
		moc_foldermodel.o
DIST          = ../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/g++.conf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/unix.conf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/linux.conf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/qconfig.pri \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/debug.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/default_post.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/moc.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/resources.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/uic.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/yacc.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/lex.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qmailcheck.pro
QMAKE_TARGET  = qmailcheck
DESTDIR       = 
TARGET        = qmailcheck

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qtincoming.h ui_prefs.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qmailcheck.pro  ../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/linux-g++-gles2/qmake.conf ../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/g++.conf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/unix.conf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/linux.conf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/qconfig.pri \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/debug.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/default_post.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/moc.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/resources.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/uic.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/yacc.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/lex.prf \
		../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/home/hardaker/.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/lib/libQtGui.prl \
		/home/hardaker/.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/lib/libQtNetwork.prl \
		/home/hardaker/.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile qmailcheck.pro
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/g++.conf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/unix.conf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/common/linux.conf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/qconfig.pri:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt_config.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/default_pre.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/debug.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/default_post.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/warn_on.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/qt.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/moc.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/resources.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/uic.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/yacc.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/lex.prf:
../../.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/home/hardaker/.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/lib/libQtGui.prl:
/home/hardaker/.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/lib/libQtNetwork.prl:
/home/hardaker/.madde/0.5/sysroots/fremantle-qt-arm-sysroot-0942/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qmailcheck.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qmailcheck1.0.0 || $(MKDIR) .tmp/qmailcheck1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qmailcheck1.0.0/ && $(COPY_FILE) --parents qtincoming.h incomingmailmodel.h mailmsg.h foldermodel.h .tmp/qmailcheck1.0.0/ && $(COPY_FILE) --parents main.cpp qtincoming.cpp incomingmailmodel.cpp mailmsg.cpp foldermodel.cpp .tmp/qmailcheck1.0.0/ && $(COPY_FILE) --parents qtincoming.ui prefs.ui .tmp/qmailcheck1.0.0/ && (cd `dirname .tmp/qmailcheck1.0.0` && $(TAR) qmailcheck1.0.0.tar qmailcheck1.0.0 && $(COMPRESS) qmailcheck1.0.0.tar) && $(MOVE) `dirname .tmp/qmailcheck1.0.0`/qmailcheck1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qmailcheck1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qtincoming.cpp moc_incomingmailmodel.cpp moc_foldermodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtincoming.cpp moc_incomingmailmodel.cpp moc_foldermodel.cpp
moc_qtincoming.cpp: ui_prefs.h \
		incomingmailmodel.h \
		mailmsg.h \
		foldermodel.h \
		qtincoming.h
	/home/hardaker/.madde/0.5/targets/fremantle-qt-0942/bin/moc $(DEFINES) $(INCPATH) qtincoming.h -o moc_qtincoming.cpp

moc_incomingmailmodel.cpp: mailmsg.h \
		foldermodel.h \
		ui_prefs.h \
		incomingmailmodel.h
	/home/hardaker/.madde/0.5/targets/fremantle-qt-0942/bin/moc $(DEFINES) $(INCPATH) incomingmailmodel.h -o moc_incomingmailmodel.cpp

moc_foldermodel.cpp: foldermodel.h
	/home/hardaker/.madde/0.5/targets/fremantle-qt-0942/bin/moc $(DEFINES) $(INCPATH) foldermodel.h -o moc_foldermodel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qtincoming.h ui_prefs.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qtincoming.h ui_prefs.h
ui_qtincoming.h: qtincoming.ui
	/home/hardaker/.madde/0.5/targets/fremantle-qt-0942/bin/uic qtincoming.ui -o ui_qtincoming.h

ui_prefs.h: prefs.ui
	/home/hardaker/.madde/0.5/targets/fremantle-qt-0942/bin/uic prefs.ui -o ui_prefs.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp qtincoming.h \
		ui_prefs.h \
		incomingmailmodel.h \
		mailmsg.h \
		foldermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qtincoming.o: qtincoming.cpp qtincoming.h \
		ui_prefs.h \
		incomingmailmodel.h \
		mailmsg.h \
		foldermodel.h \
		ui_qtincoming.h \
		moc_qtincoming.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtincoming.o qtincoming.cpp

incomingmailmodel.o: incomingmailmodel.cpp incomingmailmodel.h \
		mailmsg.h \
		foldermodel.h \
		ui_prefs.h \
		moc_incomingmailmodel.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o incomingmailmodel.o incomingmailmodel.cpp

mailmsg.o: mailmsg.cpp mailmsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mailmsg.o mailmsg.cpp

foldermodel.o: foldermodel.cpp foldermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o foldermodel.o foldermodel.cpp

moc_foldermodel.o: moc_foldermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_foldermodel.o moc_foldermodel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

